### PR TITLE
Enhancement: Run linter on Travis

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] changes directories in `before_script` section
* [x] runs the linter on Travis

### CODE REVIEW

**Comment by localheinz** [comment]
@mattmillr 

I have no idea why this fails - or doesn't fail on Python 2.7 (see https://travis-ci.org/refinery29/chassis/builds/69507698).

**Comment by mattmillr** [comment]
Weird. Python 2.6 fails on a pretty crazy syntax error in the pylint package itself (in what universe was `{'disable', 'enable'}` ever valid python??)

Python 3.X fails because the pylint dependency is not installed.

I'll dig deeper into both of these, as linting in Travis is a Very Good Idea™.

**Comment by mattmillr** [comment]
Travis CI doesn't seem to be behaving right now, so I'm going to hold off on this for a bit. I'll pick it back up tomorrow.

**Comment by localheinz** [comment]
@mattmillr 

Hey, thank you! Didn't mean to interrupt your work with opening this PR!

**Comment by mattmillr** [comment]
@localheinz I think I got it figured out...

@rcatlin can you take a look at this and +1? I'm too involved to sign off now...

**Comment by mattmillr** [comment]
I made two major changes:

* Moved the install commands into a script that checks the Python version and uses the right pip/pip3 command for each version

* Added version checking logic to lint.py to skip linting for unsupported Python versions, and used the six library to make print statements compatible across versions.

**Comment by mattmillr** [comment]
Oh, and I added `sudo: false` so that Travis CI uses a container-based deployment, which should be faster.

**Comment by rcatlin** [comment]
:+1:

**Comment by localheinz** [comment]
@mattmillr @rcatlin 

:+1: Nice!

**Pull request merged**
